---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../namespace.yaml
  - ../base/
  - ../base/placement/

patches:
  - target:
      kind: PlacementRule
    patch: |-
      - op: replace
        path: /metadata/name
        value: lab-policies-plmr
      - op: add
        path: /spec/clusterSelector/matchExpressions/0/values
        value:
          - lab-clusterset
  - target:
      kind: PolicySet
    patch: |-
      - op: replace
        path: /metadata/name
        value: lab-policyset
      - op: add
        path: /spec/description
        value: "Policy Set for ACM lab cluster"
      - op: add
        path: /spec/policies
        value:
          - policy-remove-kubeadmin
          - policy-etcd-encryption
  - target:
      kind: PlacementBinding
    patch: |-
      - op: replace
        path: /metadata/name
        value: lab-policies-placementbinding
      - op: add
        path: /placementRef/name
        value: lab-policies-plmr
      - op: add
        path: /subjects/0/name
        value: lab-policyset
