---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./acm-policies.yaml
  - ./cluster-config.yaml
  - ./nonprod-import-and-plmr-config.yaml
  - ./prod-import-and-plmr-config.yaml

