---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/acm-config.yaml
  - ../base/operators.yaml
  - ../base/workloads.yaml
  - ./hubcluster
  - ./managedclusters

  