---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-common-cluster-config
  namespace: openshift-gitops
spec:
  generators:
    - matrix:
        generators:
          - clusterDecisionResource:
              configMapRef: acm-placement
              labelSelector:
                matchLabels:
                  cluster.open-cluster-management.io/placement: prod-clusterset
              requeueAfterSeconds: 3600
          - git:
              repoURL: https://github.com/Vikaspogu/acm-folder-structure.git
              revision: master
              directories:
                - path: managedclusters/prod/common/cluster-config/*
  template:
    metadata:
      name: 'prod-common-{{name}}-{{path.basename}}'
    spec:
      destination:
        server: "{{server}}"
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        path: "{{path}}"
        repoURL: "https://github.com/Vikaspogu/acm-folder-structure.git"
        targetRevision: "master"
