---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/clustersets/
namePrefix: prod-

patches:
  - target:
      kind: ManagedClusterSetBinding
      name: clusterset
    patch: |-
      - op: add
        path: /spec/clusterSet
        value: prod-clusterset
  - target:
      kind: Placement
      name: clusterset
    patch: |-
      - op: add
        path: /spec/predicates/0/requiredClusterSelector/labelSelector/matchExpressions/0/values
        value:
          - prod-clusterset
  - target:
      kind: GitOpsCluster
      name: acm-importer
    patch: |-
      - op: add
        path: /spec/placementRef/name
        value: prod-clusterset
