---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-acm-policies
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: hubcluster/acm/policies/lab
    repoURL: "https://github.com/Vikaspogu/acm-folder-structure.git"
    targetRevision: "master"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
