---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/import/
  - ../../base/plmr/

patches:
  - target:
      kind: ManagedCluster
    patch: |-
      - op: add
        path: /metadata/name
        value: lab-aro
      - op: add
        path: /metadata/labels/name
        value: lab-aro
      - op: add
        path: /metadata/labels/cluster.open-cluster-management.io~1clusterset
        value: lab-clusterset
  - target:
      kind: KlusterletAddonConfig
    patch: |-
      - op: add
        path: /metadata/name
        value: lab-aro
      - op: add
        path: /metadata/namespace
        value: lab-aro
      - op: add
        path: /spec/clusterName
        value: lab-aro
      - op: add
        path: /spec/clusterNamespace
        value: lab-aro
      - op: add
        path: /spec/clusterLabels/name
        value: lab-aro
      - op: add
        path: /spec/clusterLabels/cluster.open-cluster-management.io~1clusterset
        value: lab-clusterset
      - op: add
        path: /spec/version
        value: 2.4.2

  # Placement rules
  - target:
      kind: PlacementRule
      name: placement-rule
    patch: |-
      - op: add
        path: /metadata/name
        value: lab-aro
      - op: add
        path: /spec/clusterSelector/matchLabels
        value:
          'name': 'lab-aro'
